/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DataQualityRouteImport } from './routes/data-quality'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as CallPerformanceRouteImport } from './routes/call-performance'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AiValidationRouteImport } from './routes/ai-validation'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityRoute = DataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const CallPerformanceRoute = CallPerformanceRouteImport.update({
  id: '/call-performance',
  path: '/call-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AiValidationRoute = AiValidationRouteImport.update({
  id: '/ai-validation',
  path: '/ai-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-validation': typeof AiValidationRoute
  '/appointments': typeof AppointmentsRoute
  '/call-performance': typeof CallPerformanceRoute
  '/coaching': typeof CoachingRoute
  '/data-quality': typeof DataQualityRoute
  '/leads': typeof LeadsRouteWithChildren
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-validation': typeof AiValidationRoute
  '/appointments': typeof AppointmentsRoute
  '/call-performance': typeof CallPerformanceRoute
  '/coaching': typeof CoachingRoute
  '/data-quality': typeof DataQualityRoute
  '/leads': typeof LeadsRouteWithChildren
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-validation': typeof AiValidationRoute
  '/appointments': typeof AppointmentsRoute
  '/call-performance': typeof CallPerformanceRoute
  '/coaching': typeof CoachingRoute
  '/data-quality': typeof DataQualityRoute
  '/leads': typeof LeadsRouteWithChildren
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/ai-validation'
    | '/appointments'
    | '/call-performance'
    | '/coaching'
    | '/data-quality'
    | '/leads'
    | '/payroll'
    | '/settings'
    | '/leads/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/ai-validation'
    | '/appointments'
    | '/call-performance'
    | '/coaching'
    | '/data-quality'
    | '/leads'
    | '/payroll'
    | '/settings'
    | '/leads/$leadId'
  id:
    | '__root__'
    | '/'
    | '/ai-chat'
    | '/ai-validation'
    | '/appointments'
    | '/call-performance'
    | '/coaching'
    | '/data-quality'
    | '/leads'
    | '/payroll'
    | '/settings'
    | '/leads/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  AiValidationRoute: typeof AiValidationRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CallPerformanceRoute: typeof CallPerformanceRoute
  CoachingRoute: typeof CoachingRoute
  DataQualityRoute: typeof DataQualityRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  PayrollRoute: typeof PayrollRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality': {
      id: '/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof DataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-performance': {
      id: '/call-performance'
      path: '/call-performance'
      fullPath: '/call-performance'
      preLoaderRoute: typeof CallPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-validation': {
      id: '/ai-validation'
      path: '/ai-validation'
      fullPath: '/ai-validation'
      preLoaderRoute: typeof AiValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
  }
}

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  AiValidationRoute: AiValidationRoute,
  AppointmentsRoute: AppointmentsRoute,
  CallPerformanceRoute: CallPerformanceRoute,
  CoachingRoute: CoachingRoute,
  DataQualityRoute: DataQualityRoute,
  LeadsRoute: LeadsRouteWithChildren,
  PayrollRoute: PayrollRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
